name: kiddo_runner
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.11.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flame: 1.37.0
  flame_audio: 2.12.1
  shared_preferences: 2.5.5
  hive: 2.2.3
  hive_flutter: 1.1.0
  provider: 6.1.5+1
  uuid: 4.3.3
  lottie: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/coins/
    - assets/images/characters/kenney_toon-characters/Male adventurer/PNG/Poses HD/
    - assets/images/characters/kenney_toon-characters/Female adventurer/PNG/Poses HD/
    - assets/images/characters/kenney_toon-characters/Zombie/PNG/Poses HD/
    - assets/images/characters/kenney_toon-characters/Robot/PNG/Poses HD/
    - assets/images/characters/kenney_toon-characters/Male person/PNG/Poses HD/
    - assets/images/characters/kenney_toon-characters/Female person/PNG/Poses HD/
    - assets/images/backgrounds/kenney_background-elements/PNG/
    - assets/images/backgrounds/kenney_background-elements/PNG/Flat/
    - assets/audio/
    - assets/licenses/
    - assets/images/reward/
    - assets/lottie/
